export { default as Hero } from "./Hero";
export { default as Skills } from "./Skills";
export { default as CareerPath } from "./CareerPath";
export { default as Projects } from "./Projects";
export { default as About } from "./About";
export { default as ResumeSection } from "./ResumeSection";
export { default as Socials } from "./Socials";
export { default as Footer } from "./Footer";
export { default as NotFound } from "./NotFound";
